import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { ordersApi } from '../api/orders';import { branchesApi } from '../api/branches';
import type { OrderListResponse,BranchResponse,CreateOrderRequest } from '../types/api';
import { useAuth } from '../auth/AuthContext';import { PERMISSIONS } from '../auth/permissions';
import { ErrorState,Spinner } from '../components/Feedback';import { getErrorMessage } from '../utils/errors';import { formatAmount } from '../utils/format';
const statuses=['Pending','Confirmed','Preparing','Ready','Served','Completed','Canceled'];
export function OrdersPage(){
 const {hasPermission,me}=useAuth();const canManage=hasPermission(PERMISSIONS.orderManage);
 const [items,setItems]=useState<OrderListResponse[]|null>(null);const [branches,setBranches]=useState<BranchResponse[]>([]);
 const [error,setError]=useState<string|null>(null);const [query,setQuery]=useState('');const [status,setStatus]=useState('All');
 const [showCreate,setShowCreate]=useState(false);const [savingId,setSavingId]=useState<number|null>(null);const [saving,setSaving]=useState(false);
 const [form,setForm]=useState<CreateOrderRequest>({orderType:'DineIn',notes:''});const [branchId,setBranchId]=useState(me?.branchId?String(me.branchId):'');
 async function load(){setError(null);try{const [o,b]=await Promise.all([ordersApi.list(),branchesApi.list()]);setItems(o);setBranches(b);if(!branchId){const first=b.find(x=>x.isActive);if(first)setBranchId(String(first.branchId))}}catch(e){setError(getErrorMessage(e))}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!branchId){setError('Choose a branch first.');return}setSaving(true);setError(null);try{const created=await ordersApi.create(Number(branchId),form);setItems(old=>[{orderId:created.orderId,orderNumber:created.orderNumber,branchName:created.branchName,tableName:created.tableName,customerName:created.customerName,status:created.status,orderType:created.orderType,totalAmount:created.totalAmount,createdAtUtc:created.createdAtUtc},...(old??[])]);setShowCreate(false);setForm({orderType:'DineIn',notes:''})}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}}
 async function changeStatus(o:OrderListResponse,next:string){setSavingId(o.orderId);setError(null);try{const updated=await ordersApi.updateStatus(o.orderId,{status:next});setItems(old=>old?.map(x=>x.orderId===o.orderId?{...x,status:updated.status,totalAmount:updated.totalAmount}:x)??[])}catch(e){setError(getErrorMessage(e))}finally{setSavingId(null)}}
 const filtered=useMemo(()=> (items??[]).filter(o=>(status==='All'||o.status.toLowerCase()===status.toLowerCase())&&[o.orderNumber,o.branchName,o.tableName??'',o.customerName??'',o.orderType].some(v=>v.toLowerCase().includes(query.toLowerCase()))),[items,status,query]);
 return <>
 <div className="admin-page-heading"><div><span className="platform-eyebrow">RESTAURANT OPERATIONS</span><h1>Orders</h1><p>Track order progress across the branches you are authorized to access.</p></div>{canManage&&<button className="btn btn-primary" onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Cancel':'＋ New order'}</button>}</div>
 {error&&<ErrorState error={error} onRetry={()=>void load()}/>}
 {showCreate&&canManage&&<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Create an order</h2><p>This creates the order header. Add line items through the order-item workflow.</p></div></div><form className="admin-form" onSubmit={create}><div className="admin-form-grid"><label>Branch<select required value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.filter(b=>b.isActive).map(b=><option key={b.branchId} value={b.branchId}>{b.name}</option>)}</select></label><label>Order type<select value={form.orderType} onChange={e=>setForm(f=>({...f,orderType:e.target.value}))}><option value="DineIn">Dine in</option><option value="Takeaway">Takeaway</option><option value="Delivery">Delivery</option></select></label></div><label>Notes (optional)<textarea rows={2} maxLength={1000} value={form.notes??''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><button className="btn btn-primary" disabled={saving||!branches.some(b=>b.isActive)}>{saving?<Spinner/>:null}{saving?'Creating…':'Create order'}</button></form></section>}
 <section className="admin-panel"><div className="admin-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, branch, table or customer…" aria-label="Search orders"/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-secondary" onClick={()=>void load()}>Refresh</button></div>
 {!items&&!error&&<div className="admin-loading"><Spinner/> Loading orders…</div>}
 {items&&<div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Branch / table</th><th>Type</th><th>Total</th><th>Status</th>{canManage&&<th>Update status</th>}</tr></thead><tbody>
 {filtered.map(o=><tr key={o.orderId}><td><strong>{o.orderNumber}</strong><small>{new Date(o.createdAtUtc).toLocaleString()}</small></td><td><strong>{o.branchName}</strong><small>{o.tableName??o.customerName??'No table/customer'}</small></td><td>{o.orderType}</td><td><strong>{formatAmount(o.totalAmount)}</strong></td><td><span className={`admin-status ${['Completed','Served'].includes(o.status)?'is-active':o.status==='Canceled'?'is-inactive':'is-pending'}`}>{o.status}</span></td>{canManage&&<td><select aria-label={`Update status for ${o.orderNumber}`} value={o.status} disabled={savingId===o.orderId} onChange={e=>void changeStatus(o,e.target.value)}>{!statuses.includes(o.status)&&<option>{o.status}</option>}{statuses.map(s=><option key={s}>{s}</option>)}</select></td>}</tr>)}
 {!filtered.length&&<tr><td colSpan={canManage?6:5}>No orders match these filters.</td></tr>}</tbody></table></div>}
 </section></>;
}
