import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { ordersApi } from '../api/orders';import { orderItemsApi } from '../api/orderItems';import { branchesApi } from '../api/branches';import { productsApi } from '../api/products';
import type { OrderListResponse,BranchResponse,CreateOrderRequest,OrderDetailsResponse,OrderItemResponse,ProductListResponse } from '../types/api';
import { useAuth } from '../auth/AuthContext';import { PERMISSIONS } from '../auth/permissions';
import { ErrorState,Spinner } from '../components/Feedback';import { getErrorMessage } from '../utils/errors';import { formatAmount } from '../utils/format';
const statuses=['Pending','Confirmed','Preparing','Ready','Served','Completed','Canceled'];
export function OrdersPage(){
 const {hasPermission,me}=useAuth();const canManage=hasPermission(PERMISSIONS.orderManage);
 const [items,setItems]=useState<OrderListResponse[]|null>(null);const [branches,setBranches]=useState<BranchResponse[]>([]);
 const [error,setError]=useState<string|null>(null);const [query,setQuery]=useState('');const [status,setStatus]=useState('All');
 const [showCreate,setShowCreate]=useState(false);const [savingId,setSavingId]=useState<number|null>(null);const [saving,setSaving]=useState(false);
 const [form,setForm]=useState<CreateOrderRequest>({orderType:'DineIn',notes:''});const [branchId,setBranchId]=useState(me?.branchId?String(me.branchId):'');
 const [selected,setSelected]=useState<OrderDetailsResponse|null>(null);const [orderItems,setOrderItems]=useState<OrderItemResponse[]>([]);const [availableProducts,setAvailableProducts]=useState<ProductListResponse[]>([]);
 const [itemProductId,setItemProductId]=useState('');const [itemQuantity,setItemQuantity]=useState('1');const [itemDiscount,setItemDiscount]=useState('0');const [detailLoading,setDetailLoading]=useState(false);
 async function load(){setError(null);try{const [o,b]=await Promise.all([ordersApi.list(),branchesApi.list()]);setItems(o);setBranches(b);if(!branchId){const first=b.find(x=>x.isActive);if(first)setBranchId(String(first.branchId))}}catch(e){setError(getErrorMessage(e))}}
 useEffect(()=>{void load()},[]);
 async function openDetails(id:number){setDetailLoading(true);setError(null);try{const d=await ordersApi.get(id);setSelected(d);const [oi,pr]=await Promise.all([orderItemsApi.list(id),productsApi.listByBranch(d.branchId)]);setOrderItems(oi);setAvailableProducts(pr);setItemProductId(pr.find(p=>p.isAvailable)?.productId.toString()??'')}catch(e){setError(getErrorMessage(e))}finally{setDetailLoading(false)}}
 async function refreshDetails(){if(!selected)return;try{const [d,oi]=await Promise.all([ordersApi.get(selected.orderId),orderItemsApi.list(selected.orderId)]);setSelected(d);setOrderItems(oi);setItems(old=>old?.map(x=>x.orderId===d.orderId?{...x,status:d.status,totalAmount:d.totalAmount}:x)??[])}catch(e){setError(getErrorMessage(e))}}
 async function create(e:FormEvent){e.preventDefault();if(!branchId){setError('Choose a branch first.');return}setSaving(true);setError(null);try{const created=await ordersApi.create(Number(branchId),form);setItems(old=>[{orderId:created.orderId,orderNumber:created.orderNumber,branchName:created.branchName,tableName:created.tableName,customerName:created.customerName,status:created.status,orderType:created.orderType,totalAmount:created.totalAmount,createdAtUtc:created.createdAtUtc},...(old??[])]);setShowCreate(false);setForm({orderType:'DineIn',notes:''});await openDetails(created.orderId)}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}}
 async function changeStatus(o:OrderListResponse,next:string){setSavingId(o.orderId);setError(null);try{const updated=await ordersApi.updateStatus(o.orderId,{status:next});setItems(old=>old?.map(x=>x.orderId===o.orderId?{...x,status:updated.status,totalAmount:updated.totalAmount}:x)??[]);if(selected?.orderId===o.orderId)setSelected(updated)}catch(e){setError(getErrorMessage(e))}finally{setSavingId(null)}}
 async function addItem(e:FormEvent){e.preventDefault();if(!selected||!itemProductId)return;setSaving(true);setError(null);try{await orderItemsApi.add(selected.orderId,{productId:Number(itemProductId),quantity:Number(itemQuantity),discountAmount:Number(itemDiscount)});await refreshDetails();setItemQuantity('1');setItemDiscount('0')}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}}
 async function editItem(item:OrderItemResponse){const q=window.prompt('New quantity',String(item.quantity));if(q===null)return;const d=window.prompt('Discount amount',String(item.discountAmount));if(d===null)return;const quantity=Number(q),discountAmount=Number(d);if(!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(discountAmount)||discountAmount<0){setError('Quantity must be positive and discount cannot be negative.');return}try{await orderItemsApi.update(item.orderItemId,{quantity,discountAmount});await refreshDetails()}catch(e){setError(getErrorMessage(e))}}
 async function removeItem(item:OrderItemResponse){if(!window.confirm(`Remove ${item.productName} from this order?`))return;try{await orderItemsApi.remove(item.orderItemId);await refreshDetails()}catch(e){setError(getErrorMessage(e))}}
 const filtered=useMemo(()=> (items??[]).filter(o=>(status==='All'||o.status.toLowerCase()===status.toLowerCase())&&[o.orderNumber,o.branchName,o.tableName??'',o.customerName??'',o.orderType].some(v=>v.toLowerCase().includes(query.toLowerCase()))),[items,status,query]);
 return <>
 <div className="admin-page-heading"><div><span className="platform-eyebrow">RESTAURANT OPERATIONS</span><h1>Orders</h1><p>Track order progress, review line items and manage order status.</p></div>{canManage&&<button className="btn btn-primary" onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Cancel':'＋ New order'}</button>}</div>
 {error&&<ErrorState error={error} onRetry={()=>void load()}/>}
 {showCreate&&canManage&&<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Create an order</h2><p>Create the order, then add products in its detail view.</p></div></div><form className="admin-form" onSubmit={create}><div className="admin-form-grid"><label>Branch<select required value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.filter(b=>b.isActive).map(b=><option key={b.branchId} value={b.branchId}>{b.name}</option>)}</select></label><label>Order type<select value={form.orderType} onChange={e=>setForm(f=>({...f,orderType:e.target.value}))}><option value="DineIn">Dine in</option><option value="Takeaway">Takeaway</option><option value="Delivery">Delivery</option></select></label></div><label>Notes (optional)<textarea rows={2} maxLength={1000} value={form.notes??''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><button className="btn btn-primary" disabled={saving||!branches.some(b=>b.isActive)}>{saving?<Spinner/>:null}{saving?'Creating…':'Create order'}</button></form></section>}
 <section className="admin-panel"><div className="admin-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, branch, table or customer…" aria-label="Search orders"/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-secondary" onClick={()=>void load()}>Refresh</button></div>
 {!items&&!error&&<div className="admin-loading"><Spinner/> Loading orders…</div>}
 {items&&<div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Branch / table</th><th>Type</th><th>Total</th><th>Status</th><th>Details</th>{canManage&&<th>Update status</th>}</tr></thead><tbody>
 {filtered.map(o=><tr key={o.orderId}><td><strong>{o.orderNumber}</strong><small>{new Date(o.createdAtUtc).toLocaleString()}</small></td><td><strong>{o.branchName}</strong><small>{o.tableName??o.customerName??'No table/customer'}</small></td><td>{o.orderType}</td><td><strong>{formatAmount(o.totalAmount)}</strong></td><td><span className={`admin-status ${['Completed','Served'].includes(o.status)?'is-active':o.status==='Canceled'?'is-inactive':'is-pending'}`}>{o.status}</span></td><td><button className="btn btn-secondary btn-sm" onClick={()=>void openDetails(o.orderId)}>View order</button></td>{canManage&&<td><select aria-label={`Update status for ${o.orderNumber}`} value={o.status} disabled={savingId===o.orderId} onChange={e=>void changeStatus(o,e.target.value)}>{!statuses.includes(o.status)&&<option>{o.status}</option>}{statuses.map(s=><option key={s}>{s}</option>)}</select></td>}</tr>)}
 {!filtered.length&&<tr><td colSpan={canManage?7:6}>No orders match these filters.</td></tr>}</tbody></table></div>}
 </section>
 {(selected||detailLoading)&&<div className="modal-backdrop" role="presentation" onClick={e=>{if(e.target===e.currentTarget){setSelected(null);setOrderItems([])}}}><section className="admin-panel order-detail-modal" role="dialog" aria-modal="true" aria-label="Order details">
 <div className="admin-panel-heading"><div><span className="platform-eyebrow">ORDER DETAILS</span><h2>{selected?selected.orderNumber:'Loading order…'}</h2><p>{selected?selected.branchName+' · '+selected.orderType:''}</p></div><button className="btn btn-secondary btn-sm" onClick={()=>{setSelected(null);setOrderItems([])}}>Close</button></div>
 {detailLoading&&!selected&&<div className="admin-loading"><Spinner/> Loading order…</div>}
 {selected&&<><div className="order-summary-grid"><div><small>Status</small><strong>{selected.status}</strong></div><div><small>Subtotal</small><strong>{formatAmount(selected.subTotal)}</strong></div><div><small>Discount</small><strong>{formatAmount(selected.discountAmount)}</strong></div><div><small>Total</small><strong>{formatAmount(selected.totalAmount)}</strong></div></div>
 <div className="admin-panel-heading"><div><h2>Order items</h2><p>Prices are calculated by the backend from the selected product.</p></div></div>
 <div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Discount</th><th>Line total</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{orderItems.map(i=><tr key={i.orderItemId}><td><strong>{i.productName}</strong></td><td>{i.quantity}</td><td>{formatAmount(i.unitPrice)}</td><td>{formatAmount(i.discountAmount)}</td><td><strong>{formatAmount(i.lineTotal)}</strong></td>{canManage&&<td><div className="plan-actions"><button className="btn btn-secondary btn-sm" onClick={()=>void editItem(i)}>Edit</button><button className="btn btn-danger-soft btn-sm" onClick={()=>void removeItem(i)}>Remove</button></div></td>}</tr>)}{!orderItems.length&&<tr><td colSpan={canManage?6:5}>No products have been added to this order yet.</td></tr>}</tbody></table></div>
 {canManage&&<form className="admin-form order-add-item" onSubmit={addItem}><h3>Add product</h3><div className="admin-form-grid"><label>Product<select required value={itemProductId} onChange={e=>setItemProductId(e.target.value)}><option value="">Choose product…</option>{availableProducts.filter(p=>p.isAvailable).map(p=><option key={p.productId} value={p.productId}>{p.name} · {formatAmount(p.price)}</option>)}</select></label><label>Quantity<input required type="number" min="0.001" step="0.001" value={itemQuantity} onChange={e=>setItemQuantity(e.target.value)}/></label></div><label>Discount amount<input type="number" min="0" step="0.01" value={itemDiscount} onChange={e=>setItemDiscount(e.target.value)}/></label><button className="btn btn-primary" disabled={saving||!availableProducts.some(p=>p.isAvailable)}>{saving?<Spinner/>:null}Add to order</button></form>}
 {selected.notes&&<div className="order-notes"><strong>Order notes</strong><p>{selected.notes}</p></div>}</>}
 </section></div>}
 </>;
}
